### ISSUE TITLE
RSA - Padding Oracle Vulnerability

### ISSUE THREAD

**Issue by paragonie-scott** [NorseBlue/Sikker#2]
https://github.com/NorseBlue/Sikker/blob/master/src/Asymmetric/Keys/PrivateKey.php#L72

See https://framework.zend.com/security/advisory/ZF2015-10

**Comment by axelitus** [comment]
Great! Thanks a lot Scott! I'll be patching the source code later on. Wasn't aware of this security issue.

Just for reference here's the explanation of the Bleichenbacher's attack: http://crypto.stackexchange.com/questions/12688/can-you-explain-bleichenbachers-cca-attack-on-pkcs1-v1-5

**Comment by paragonie-scott** [comment]
For the record: I'm using this vulnerability as evidence for "we need to fix the OpenSSL extension to be more secure by default" arguments. Almost nobody gets this right.

**Comment by axelitus** [comment]
I agree... the defaults should have a sufficient level of security (and the question would be "what is a sufficient level of security", but that's for another discussion hehe). If the extension does not provide this by default we should take some considerations in our libraries, so thanks a lot for bringing this issue up!

**Comment by axelitus** [comment]
I'm already working on a patch. The source code has been modified with the Zend solution by adding a padding parameter and defaulting it to OPENSSL_PKCS1_OAEP_PADDING. The codes is finished, but now I'm getting the following error in the tests: _error:04066076:rsa routines:RSA_EAY_PRIVATE_ENCRYPT:unknown padding type_

I need to check why this is happening, it may be because I'm currently on windows and some libraries are not installed? Don't know, need to Google around.

**Comment by paragonie-scott** [comment]
Are you using FIPS mode OpenSSL and/or an ancient version of OpenSSL?

**Comment by axelitus** [comment]
I'm using XAMPP 7.0.8 on Windows at the moment with OpenSSL/1.0.2e (I know... it's a fast but crappy way of doing this, but at the moment is what I have here at the office... I'm migrating to vagrant when I got time). I'm testing this on linux later on because to be honest I don't trust that much in my setup 🙈

**Comment by axelitus** [comment]
I know now what I was doing wrong. I added the padding scheme to `PrivateKey::encrypt()`, when `openssl_private_encrypt()` does not support that padding type: http://php.net/manual/en/function.openssl-private-encrypt.php
It had nothing to do with my setup (though I finally created a vagrant configuration for testing purposes).

OPENSSL_PKCS1_OAEP_PADDING support is only for:
`PublicKey::encrypt()` -> `PrivateKey::decrypt()`
